name: Super_linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: unbuntu:latest
    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEAFULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

